# Hardware
#"depth_module.emitter_enabled": 0  # uncomment to use external IR projector
# Data Streams
"enable_color": true  # only for overlay
"color_qos": "SENSOR_DATA"  # best-effort, smaller queue
"enable_depth": false
"enable_infra1": true
"infra1_qos": "SENSOR_DATA"
"enable_infra2": true
"infra2_qos": "SENSOR_DATA"
"enable_gyro": true
"gyro_qos": "SENSOR_DATA"
"enable_accel": true
"accel_qos": "SENSOR_DATA"
# Post-processing
"unite_imu_method": 2
"enable_sync": true
